### PR TITLE
Introduced compatibility for ESP32 boards.

### PR DESCRIPTION
**Pull request by maker-ATOM**
This pull request adds support for ESP32 boards and provides the flexibility to associate channels with the specified PWM pin.

### CODE REVIEW

**Comment by waiweng83** [comment]
I'm sorry that I can't merge this PR as it's not backward compatible with the earlier version.
Feel free to fork it.

Anyway, I just merged another PR that's also added ESP32 support. Please try it out.

Thanks.

**Comment by maker-ATOM** [comment]
There is an issue with the commit 0251830233152efcd3228638115fe45053e5b779 . To drive pins in PWM mode in ESP32, PWM channels needs to be assigned, which is currently missing in the latest version of the library. 
The proposed Pull Request solves this issue by introducing another parameter that needs to be passed **only** while working with ESP32, regarding **backward compatibility** the parameter - channel is a default parameter hence codebase for Arduinos need not to be changed. New codebase created for ESP32 needs to be updated, as for every instance created of the class needs to have different channel assigned.

**Comment by waiweng83** [comment]
Can you please create another PR based on the latest code?
Thanks.

**Comment by maker-ATOM** [comment]
Sure, but the forked version(maker-ATOM:master) is 2 commits ahead and 4 commits behind CytronTechnologies:master so the PR will create a merge conflict.

**Pull request closed without merging**
